name: bluecorridor
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - xarray
  - netcdf4
  - zarr
  - dask
  - numpy
  - pandas
  - pyproj
  - rasterio
  - shapely
  - geopandas
  - requests
  - pyyaml
  - tqdm
  - pip
  - pip:
    - opendrift
    - cartopy
    - pyresample
